[package]
name = "voice_assistant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
openai_rs = { path = "./OpenAI-Rust" }
elevenlabs_rs = { path = "./elevenlabs-api-rust" }